import Head from "next/head";
import { useState, useEffect } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import Image from "next/image";
import { Navbar } from "@frontend/components/Nav";
import { UsernamePopup } from "@frontend/components/UsernamePopup";
import log from "@shared/logger";
import { FaPlus } from "react-icons/fa";

export default function UserProfile() {
	const { data: session } = useSession();
	const [user, setData] = useState(null);
	const [showUsernameInput, setShowUsernameInput] = useState(false);
	const searchedName = useRouter().query["user"];
	const myEmail = session?.user.email;

	useEffect(() => {
		fetch("/api/profile", {
			body: JSON.stringify({ searchedName, myEmail }),
			method: "POST",
		}).then(async (res) => {
			if (searchedName === undefined) return;
			setData(await res.json());
		});
	}, [searchedName]);

	useEffect(() => {
		fetch("/api/profileSetup", {
			body: JSON.stringify({ myEmail, add: false }),
			method: "POST",
		}).then(async (res) => {
			var user = await res.json();
			log.debug(user);
			if (user.success === false) {
				setShowUsernameInput(true);
			}
		});
	}, [session, showUsernameInput, myEmail]);

	const addFriend = (e) => {
		// const username = e.target.value
		// console.log(username)
		// fetch("/api/manageFriend", {
		// 	body: JSON.stringify({ username, myEmail }),
		// 	method: "POST",
		// }).then(async (res) => {
		// 	var user = await res.json();
		// 	log.debug(user);
		// });
	};

	const links = [
		{ id: "1", text: "Home", path: "/" },
		{ id: "2", text: "Friends", path: "/friends" },
	];

	if (user === null) return;

	return (
		<div>
			<Head>
				<title>{searchedName}&#39;s Profile</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Navbar links={links} />
				{showUsernameInput && (
					<UsernamePopup activate={showUsernameInput} />
				)}
				{user.user && (
					<div className="mx-auto mt-10 pb-10 pt-10">
						<div className="h-48 w-48 mx-auto">
							<Image
								className="rounded-full"
								src={user.user.pfp}
								alt="Profile picture"
								width={256}
								height={256}
								objectFit="contain"
							/>
						</div>
						<div className="text-nord_light-300 text-center mt-10 text-xl">
							<ul className="mb-4 text-3xl">
								<li>
									<span className="font-bold">
										{user.user.name}{" "}
									</span>
									<span className="text-nord_blue-300">
										@{user.user.username}
									</span>
								</li>
							</ul>
							{user.sessionedUser !== true && (
								<>
									<button
										onClick={addFriend}
										className="float-center ml-4 mt-4 text-nord_light-300 bg-nord_dark-100 pt-1 pb-1 pl-3 pr-3 rounded-lg"
									>
										Block
									</button>

									<button
										value={user.user.username}
										onClick={addFriend}
										className="float-center ml-4 mt-4 text-nord_dark-200 bg-nord_green p-3 rounded-lg"
									>
										<FaPlus />
									</button>
									<button
										onClick={addFriend}
										className="float-center ml-4 mt-4 text-nord_light-300 bg-nord_red pt-1 pb-1 pl-3 pr-3 rounded-lg"
									>
										Report
									</button>
								</>
							)}
						</div>
					</div>
				)}

				{!user.user && (
					<div className="grid h-screen place-items-center text-nord_light-300 text-center">
						<h1 className="font-bold text-3xl">
							No User With That Name
						</h1>
					</div>
				)}
			</main>
		</div>
	);
}
