import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { Navbar } from "@frontend/components/Nav";

export default function Profile() {
	const { data: session, status } = useSession();
	const links = [
		{ id: "1", text: "Home", path: "/" },
		{ id: "2", text: "Friends", path: "/friends" },
	];

	return (
		<div>
			<Head>
				<title>{session?.user.name}&#39;s Profile</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="bg-nord_dark-100">
				<Navbar links={links} />
			</main>
		</div>
	);
}
