import Head from "next/head";
import { useSession } from "next-auth/react";
import { useEffect, useState } from "react";
import { Navbar } from "@frontend/components/Nav";
import { UsernamePopup } from "@frontend/components/UsernamePopup";
import log from "@shared/logger";

export default function Home() {
	const { data: session } = useSession();
	const [showUsernameInput, setShowUsernameInput] = useState(false);
	var [username, setUsername] = useState();
	log.debug(session);
	const email = session?.user.email;
	useEffect(() => {
		fetch("/api/profileSetup", {
			body: JSON.stringify({ email, add: false }),
			method: "POST",
		}).then(async (res) => {
			var user = await res.json();
			log.debug(user);
			if (user.success === false) {
				setShowUsernameInput(true);
			}
		});
	}, [session, showUsernameInput, email]);

	useEffect(() => {
		fetch("/api/getUserdata", {
			body: JSON.stringify({ email }),
			method:'POST'
		}).then(async (res) => {
			setUsername(await res.json())
		})
	}, [session])

	const links = [
		{ id: "1", text: "Friends", path: "/friends" },
		{ id: "2", text: "Profile", path: `/profile/${username?.user.username}` },
	];

	log.debug(showUsernameInput);
	return (
		<div>
			<Head>
				<title>Home</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Navbar links={links} />
				{log.debug(showUsernameInput)}
				{showUsernameInput && (
					<UsernamePopup activate={showUsernameInput} />
				)}
				<h1 className="text-center text-nord_light-300 font-bold text-xl pt-10">
					Welcome {session?.user.name}
				</h1>
			</main>
		</div>
	);
}
