import Head from "next/head";
import { useState, useEffect } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import Image from "next/image";
import { Navbar } from "@frontend/components/Nav";
import { UsernamePopup } from "@frontend/components/UsernamePopup";

export default function UserProfile() {
	const { data: session } = useSession();
	const [user, setData] = useState(null);
	const [showUsernameInput, setShowUsernameInput] = useState(false);
	const searchedName = useRouter().query["user"];
	const myName = session?.user.name;
	const email = session?.user.email;

	useEffect(() => {
		fetch("/api/profile", {
			body: JSON.stringify({ searchedName, myName }),
			method: "POST",
		}).then(async (res) => {
			if (searchedName === undefined) return;
			console.log("hi");
			setData(await res.json());
		});
	}, [searchedName, myName]);

	useEffect(() => {
		fetch("/api/profileSetup", {
			body: JSON.stringify({ email, add: false }),
			method: "POST",
		}).then(async (res) => {
			var user = await res.json();
			console.log(user);
			if (user.success === false) {
				setShowUsernameInput(true);
			}
		});
	}, [session, showUsernameInput, email]);

	const links = [
		{ id: "1", text: "Home", path: "/" },
		{ id: "2", text: "Friends", path: "/friends" },
	];

	if (user === null) return;

	return (
		<div>
			<Head>
				<title>{searchedName}&#39;s Profile</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Navbar links={links} />
				{showUsernameInput && (
					<UsernamePopup activate={showUsernameInput} />
				)}
				{user.user && (
					<div className="mx-auto mt-10 pb-10 pt-10">
						<div className="h-48 w-48 mx-auto">
							<Image
								className="rounded-full"
								src={user.user.pfp}
								alt="Profile picture"
								width={256}
								height={256}
								objectFit="contain"
							/>
						</div>
						<h1 className="text-nord_light-300 text-center mt-10 text-xl font-bold">
							<ul>
								<li>Nickname: {user.user.name}</li>
								<li>Username: {user.user.username}</li>
							</ul>
						</h1>
					</div>
				)}

				{!user.user && (
					<div className="grid h-screen place-items-center text-nord_light-300 text-center">
						<h1 className="font-bold text-3xl">
							No User With That Name
						</h1>
					</div>
				)}
			</main>
		</div>
	);
}
