import Head from "next/head";
import { useState, useEffect } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import { Navbar } from "../../components/Nav";
import Image from "next/image";

export default function UserProfile() {
	const { data: session, status } = useSession();
	const [isLoading, setLoading] = useState(false);
	const [user, setData] = useState(null);
	const searchedName = useRouter().query["user"];
	const myName = session?.user.name;

	useEffect(() => {
		setLoading(true);
		fetch("/api/profile", {
			body: JSON.stringify({ searchedName, myName }),
			method: "POST",
		}).then(async (res) => {
			if (searchedName === undefined) return;
			console.log("hi");
			setData(await res.json());
			setLoading(false);
		});
	}, [searchedName, myName]);
	const links = [
		{ id: "1", text: "Home", path: "/" },
		{ id: "2", text: "Friends", path: "/friends" },
	];
	if (user === null) return;
	return (
		<div>
			<Head>
				<title>{searchedName}&#39;s Profile</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Navbar links={links} />

				{user.user && (
					<div className="mx-auto mt-10 pb-10 pt-10">
						<div className="h-48 w-48 mx-auto">
							<Image
								className="rounded-full"
								src={user.user.pfp}
								alt="Profile picture"
								width={256}
								height={256}
								objectFit="contain"
							/>
						</div>
						<h1 className="text-nord_light-300 text-center mt-10 text-xl font-bold">
							Username: {user.user.name}
						</h1>
					</div>
				)}

				{!user.user && (
					<div className="grid h-screen place-items-center text-nord_light-300 text-center">
						<h1 className="font-bold text-3xl">
							No User With That Name
						</h1>
					</div>
				)}
			</main>
		</div>
	);
}
