import Head from "next/head";
import { useSession } from "next-auth/react";
import { useState, useEffect } from "react";
import { Navbar } from "../components/Nav";

export default function Friends() {
	const [userFriends, setData] = useState(null);
	const [isLoading, setLoading] = useState(false);
	const { data: session } = useSession();
	const email = session?.user.email;
	const name = session?.user.name;
	console.log(email);
	const links = [
		{ id: "1", text: "Home", path: "/" },
		{ id: "2", text: "Profile", path: "/profile" },
	];

	useEffect(() => {
		setLoading(true);
		fetch("/api/friends", {
			body: JSON.stringify({ email, name }),
			method: "POST",
		}).then(async (res) => {
			if (email === undefined) return;
			console.log("hi");
			setData(await res.json());
			setLoading(false);
		});
	}, [session, email, name]);

	console.log(!isLoading);
	if (userFriends === null) return;
	console.log(userFriends);
	return (
		<div>
			<Head>
				<title>Friends</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Navbar links={links} />
				<h1 className="text-center text-nord_light-300 font-bold text-xl pt-10">
					{session?.user.name}&#39;s Friends
				</h1>
				<div className="grid place-items-center pt-5">
					<form>
						<input
							placeholder="Search"
							className="bg-nord_dark-200 outline-none rounded-lg text-nord_light-300 pt-2 pb-2 pl-4 pr-4"
						></input>
					</form>
					<div className="pt-5 pb-5 pl-10 pr-10 w-screen mt-8">
						<ol id="friends">
							{userFriends.friends.map((name) => (
								<li
									key={name.name}
									className="text-nord_light-300 pt-3 pb-3"
								>
									{name.name}

									<hr className="border-nord_dark-100 mt-2" />
								</li>
							))}
						</ol>
					</div>
				</div>
			</main>
		</div>
	);
}
