import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { Navbar } from "../components/Nav.jsx";

export default function Home() {
	const { data: session, status } = useSession();
	console.log(session);
	const links = [
		{ id: "1", text: "Friends", path: "/friends" },
		{ id: "2", text: "Profile", path: "/profile" },
	];

	return (
		<div>
			<Head>
				<title>Home</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Navbar links={links} />
				<h1 className="text-center text-nord_light-300 font-bold text-xl pt-10">
					Welcome {session?.user.name}
				</h1>
			</main>
		</div>
	);
}
